<a href="https://colab.research.google.com/github/gchn24/DS-Notes/blob/main/ChiSquare_Code_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import chisquare, chi2, chi2_contingency

In [ ]:
!gdown 1hR_60jiBA_-NYy4RA9vKjYelxkwXcfLF -O 'aerofit.csv'

Downloading...
From: https://drive.google.com/uc?id=1hR_60jiBA_-NYy4RA9vKjYelxkwXcfLF
To: /content/aerofit.csv
100% 7.28k/7.28k [00:00<00:00, 32.0MB/s]


# Coin toss

In [ ]:
# H0: Coin is fair
# Ha: Coin is biased

alpha = 0.05

obs = [28, 22]
exp = [25, 25]

chisquare(obs, exp)


chi_stat, p_value = chisquare(obs, exp)

print(p_value)
print(chi_stat)
if p_value < alpha:
    print("Reject H0")
else:
    print("Fail to reject H0")
    print("Coin is fair")

0.3961439091520741
0.72
Fail to reject H0
Coin is fair


In [ ]:
chi_stat = (28 - 25)**2/25 + (22 - 25)**2 /25 # chi2stat
chi_stat

0.72

In [ ]:
p_value = 1 - chi2.cdf(chi_stat, df = 1)
p_value

0.3961439091520741

In [ ]:
# H0: Coin is fair
# Ha: Coin is biased

alpha = 0.05

obs = [45, 5]
exp = [25, 25]

chisquare(obs, exp)


chi_stat, p_value = chisquare(obs, exp)

print(p_value)
print(chi_stat)
if p_value < alpha:
    print("Reject H0, coin is biased")
else:
    print("Fail to reject H0")
    print("Coin is fair")

1.5417257900280013e-08
32.0
Reject H0, coin is biased


# Gender Vs Offline and Online

In [ ]:
chi_stat = 57
dof = 1

alpha = 0.05

# H0 : Gender and preference are independent
# HA : Gender and preference are dependent

p_value  = 1 - chi2.cdf(chi_stat, dof)
p_value

4.363176486776865e-14

In [ ]:
# H0: Gender and preference are independent
# HA: Preference depends on gender

observed = [
    [527, 72],
    [206, 102],
]

chi_stat, p_value, df, exp_freq = chi2_contingency(observed) # chi_stat, p_value, df, expected values

print(chi_stat)
print(p_value)
print(df)
print(exp_freq)

if p_value < 0.05:
    print("Reject H0")

57.04098674049609
4.268230756875865e-14
1
[[484.08710033 114.91289967]
 [248.91289967  59.08710033]]
Reject H0


# Aerofit

In [ ]:
df_aerofit = pd.read_csv("aerofit.csv")

In [ ]:
df_aerofit

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0     KP281   18    Male         14        Single      3        4   29562   
1     KP281   19    Male         15        Single      2        3   31836   
2     KP281   19  Female         14     Partnered      4        3   30699   
3     KP281   19    Male         12        Single      3        3   32973   
4     KP281   20    Male         13     Partnered      4        2   35247   
..      ...  ...     ...        ...           ...    ...      ...     ...   
175   KP781   40    Male         21        Single      6        5   83416   
176   KP781   42    Male         18        Single      5        4   89641   
177   KP781   45    Male         16        Single      5        5   90886   
178   KP781   47    Male         18     Partnered      4        5  104581   
179   KP781   48    Male         18     Partnered      4        5   95508   

     Miles  
0      112  
1       75  
2       66  
3       85  
4       47  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[180 rows x 9 columns]

In [ ]:
gender_product = pd.crosstab(index=df_aerofit['Gender'],
            columns=df_aerofit['Product'])
gender_product

Product  KP281  KP481  KP781
Gender                      
Female      40     29      7
Male        40     31     33

In [ ]:
# H0 : Gender does not impact buying of product
# HA : Gender impacts buying of product

alpha = 0.05

chi_stat, p_value, df, exp_value  = chi2_contingency(gender_product)

print(chi_stat)
print(p_value)
print(df)
print(exp_value)

if p_value < 0.05:
    print("Reject H0")
    print("Gender impacts product")

else :
    print("Gender does not impact buying of product")


12.923836032388664
0.0015617972833158714
2
[[33.77777778 25.33333333 16.88888889]
 [46.22222222 34.66666667 23.11111111]]
Reject H0
Gender impacts product


In [ ]:
Q1 = pd.DataFrame([['Single','Abstain']]*67 + [['Single','1-60']]*213 + [['Single','Over60']]*74 + [['Married','Abstain']]*411 + [['Married','1-60']]*633 + [['Married','Over60']]*129 + [['Widowed','Abstain']]*85 + [['Widowed','1-60']]*51 + [['Widowed','Over60']]*7 + [['Divorced','Abstain']]*27 + [['Divorced','1-60']]*60 + [['Divorced','Over60']]*15 ,columns=['MaritalStatus','DrinksPerMonth'])

In [ ]:
Q1CrossTab = pd.crosstab(index = Q1['MaritalStatus'], columns = Q1['DrinksPerMonth'])

In [ ]:
# H0 : Marital Status doesnot impact Alcohol Consumption
# HA : It does impact

alpha = 0.05

chi_stat, p_value, df, exp_value  = chi2_contingency(Q1CrossTab)

print(chi_stat)
print(p_value)
print(df)
print(exp_value)

if p_value < 0.05:
    print("Reject H0")

else :
    print("Unable to reject H0")


94.26880078578765
3.925170647869838e-18
6
[[ 55.08690745  33.96162528  12.95146727]
 [633.49943567 390.55869074 148.94187359]
 [191.18397291 117.86681716  44.94920993]
 [ 77.22968397  47.61286682  18.15744921]]
Reject H0


In [ ]:
#Q2

Q2 = pd.DataFrame([['LessHS','Diabetes']]*33 + [['LessHS','NoDiabetes']]*218 + [['HSGrad','Diabetes']]*25 + [['HSGrad','NoDiabetes']]*389 + [['SomeCollege','Diabetes']]*20 + [['SomeCollege','NoDiabetes']]*393 + [['CollegeGrad','Diabetes']]*17 + [['CollegeGrad','NoDiabetes']]*178,columns=['Education','DiabeticState'])

In [ ]:
Q2CrossTab = pd.crosstab(index = Q2['Education'], columns = Q2['DiabeticState'])

In [ ]:
# H0 : Education does not impact diabetic state
# HA : It does impact

alpha = 0.01

chi_stat, p_value, df, exp_value  = chi2_contingency(Q2CrossTab)

print(chi_stat)
print(p_value)
print(df)
print(exp_value)

if p_value < alpha:
    print("Reject H0")

else :
    print("Unable to reject H0")


17.51186847271713
0.000554511571355531
3
[[ 14.55223881 180.44776119]
 [ 30.89552239 383.10447761]
 [ 18.73134328 232.26865672]
 [ 30.82089552 382.17910448]]
Reject H0


In [ ]:
#Q3

Q3 = pd.DataFrame([['R','B']]*77 + [['R','S']]*149 + [['R','A']]*78 + [['NR','B']]*23 + [['NR','S']]*56 + [['NR','A']]*36 + [['A','B']]*8 + [['A','S']]*24 + [['A','A']]*29 + [['DK','B']]*6 + [['DK','S']]*15 + [['DK','A']]*8,columns=['Religiosity','Education'])

In [ ]:
Q3CrossTab = pd.crosstab(index = Q3['Religiosity'], columns = Q3['Education'])

In [ ]:
# H0 : Religiosity does not impact education
# HA : It does impact

alpha = 0.05

chi_stat, p_value, df, exp_value  = chi2_contingency(Q3CrossTab)

print(chi_stat)
print(p_value)
print(df)
print(exp_value)

if p_value < alpha:
    print("Reject H0")

else :
    print("Unable to reject H0")


13.322313008960624
0.038193742691133854
6
[[ 18.09626719  13.66208251  29.24165029]
 [  8.60314342   6.49508841  13.90176817]
 [ 34.11591356  25.75638507  55.12770138]
 [ 90.18467583  68.08644401 145.72888016]]
Reject H0


In [ ]:
#Q4

observed = [[335, 348, 318],
[35, 23, 50]]

# H0 : No Association between Response and Region
# HA : There is association

alpha = 0.01

chi_stat, p_value, df, exp_value  = chi2_contingency(observed)

print(chi_stat)
print(p_value)
print(df)
print(exp_value)

if p_value < alpha:
    print("Reject H0")

else :
    print("Unable to reject H0")



11.519544916042339
0.003151828690194211
2
[[333.96753832 334.87015329 332.16230839]
 [ 36.03246168  36.12984671  35.83769161]]
Reject H0


In [ ]:
#Q5

observed = [[6, 38, 31],
[14, 31, 4],
[50, 50, 5]]

# H0 : No Association between Usage and Age
# HA : There is association

alpha = 0.01

chi_stat, p_value, df, exp_value  = chi2_contingency(observed)

print(chi_stat)
print(p_value)
print(df)
print(exp_value)

if p_value < alpha:
    print("Reject H0")

else :
    print("Unable to reject H0")



60.74604310295546
0.0
4
[[22.92576419 38.97379913 13.10043668]
 [14.97816594 25.4628821   8.55895197]
 [32.09606987 54.56331878 18.34061135]]
Reject H0


In [ ]:
#Q6

observed = [[75, 106, 46],
[106, 161, 61],
[98, 183, 52],
[48, 102, 14]]

# H0 : No Association between Income and Residence
# HA : There is association

alpha = 0.05

chi_stat, p_value, df, exp_value  = chi2_contingency(observed)

print(chi_stat)
print(p_value)
print(df)
print(exp_value)

if p_value < alpha:
    print("Reject H0")

else :
    print("Unable to reject H0")



15.727554171801787
0.015293451318673136
6
[[ 70.55988593 119.11026616  37.32984791]
 [101.95437262 172.10646388  53.9391635 ]
 [103.50855513 174.73003802  54.76140684]
 [ 50.97718631  86.05323194  26.96958175]]
Reject H0
