<a href="https://colab.research.google.com/github/gchn24/DS-Notes/blob/main/Numpy5_PostRead_MiscTopics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Content

- **Expanding Dimension**
    - `None`

- **Ravel**
    - `ravel()`


In [ ]:
import numpy as np

## Expanding Dimensions

We can also use None instead of `np.newaxis` to expand dimension

In [ ]:
arr=np.arange(0,6)

In [ ]:
arr[:, None] # eqvivalent to arr[:, np.newaxis] or np.expand_dims(arr, axis =1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr[None, :] # eqvivalent to arr[np.newaxis, : ] or np.expand_dims(arr, axis =0)

array([[0, 1, 2, 3, 4, 5]])

### Ravel

Do you remember flatten function? It is used to convert nD array to 1D array.



#### Let's take our $3\times4$ matrix `A` 

In [ ]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A.flatten() 

# Gives 1D vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### There's another function which does the same job: `ravel()`

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Why there are two functions for doing same thing ? 

**Flatten returns copy of the array whereas ravel returns view of the array** 
**It means if i ravel an array and modify the raveled array, it'll change the original array as well**

In [ ]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
B = A.flatten()
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
B[0] = 55
B

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
C = A.ravel()
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
C[0] = 55
C

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
A

array([[55,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Notice how values of A changed when we changed C array.